import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import { useEffect, useState } from "react";
import PortfolioCard from "../components/PortfolioCard";
const graphcms = new GraphQLClient(
  "https://api-ap-south-1.graphcms.com/v2/cl4ba8lgp2tkg01xu6yzc6oz2/master"
); //connecting to the cms

const QUERY = gql`
  {
    posts {
      title
      categoryref {
        categoryName
      }
      coverPhoto {
        id
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((post) => (
          <PortfolioCard
            title={post.title}
            category={post.categoryref.categoryName}
            CoverPhoto={post.coverPhoto}
            key={post.id}
            datePublished={post.datePublished}
            slug={post.slug}
          />
        ))}
      </main>
    </div>
  );
}
